--------------------------------------------------------
--  File created - Tuesday-May-22-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALMACEN
--------------------------------------------------------

  CREATE TABLE "LANA"."ALMACEN" 
   (	"EXISTENCIA" NUMBER(*,0), 
	"IDCIGARRILLO" NUMBER(*,0), 
	"NUMFISCAL" VARCHAR2(20 BYTE), 
	"IDALMACEN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CIGARRILLO
--------------------------------------------------------

  CREATE TABLE "LANA"."CIGARRILLO" 
   (	"IDCIGARRILLO" NUMBER(*,0), 
	"CONTAMINANTE" NUMBER(*,0), 
	"FILTRO" NUMBER(*,0), 
	"HOJA" NUMBER(*,0), 
	"MENTOLADO" NUMBER, 
	"MARCA" VARCHAR2(30 BYTE), 
	"MED_CALIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPRA
--------------------------------------------------------

  CREATE TABLE "LANA"."COMPRA" 
   (	"NUMCOMPRA" NUMBER(*,0), 
	"FECHAC" DATE, 
	"PRECIOCOMPRA" FLOAT(126), 
	"CANTIDAD" NUMBER(*,0), 
	"NUMFISCAL" VARCHAR2(30 BYTE), 
	"IDCIGARRILLO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTANCO
--------------------------------------------------------

  CREATE TABLE "LANA"."ESTANCO" 
   (	"NUMEXP" NUMBER(*,0), 
	"NUMFISCAL" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"PROVINCIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FABRICANTE
--------------------------------------------------------

  CREATE TABLE "LANA"."FABRICANTE" 
   (	"NOMBRE_FABRICANTE" VARCHAR2(50 BYTE), 
	"IDFABRICANTE" NUMBER, 
	"PAIS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MANUFACTURA
--------------------------------------------------------

  CREATE TABLE "LANA"."MANUFACTURA" 
   (	"MARCA" VARCHAR2(30 BYTE), 
	"CARTON" NUMBER, 
	"EMBALAJE" NUMBER, 
	"IDFABRICANTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "LANA"."VENTA" 
   (	"NUMVENTA" NUMBER(*,0), 
	"NUMFISCAL" VARCHAR2(30 BYTE), 
	"IDCIGARRILLO" NUMBER, 
	"PRECIOVENTA" NUMBER, 
	"CANTIDAD" NUMBER, 
	"FECHAV" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into LANA.ALMACEN
SET DEFINE OFF;
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (200,0,'11111',0);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,1,'11111',1);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (143,2,'11111',2);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (234,3,'11111',3);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (12,5,'11111',5);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (65,6,'11111',6);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (321,7,'11111',7);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,8,'11111',8);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (231,9,'11111',9);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,10,'11111',10);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,12,'11111',11);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (214,13,'11111',12);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (126,14,'11111',13);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (301,15,'11111',14);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11111',15);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (100,0,'11112',16);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (134,1,'11112',17);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11112',18);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11112',19);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11112',20);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (112,5,'11112',21);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (235,6,'11112',22);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (421,7,'11112',23);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (433,8,'11112',24);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (231,9,'11112',25);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,10,'11112',26);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (423,12,'11112',27);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (14,13,'11112',28);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (136,14,'11112',29);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,15,'11112',30);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11112',31);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (200,0,'11113',32);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,1,'11113',33);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (243,2,'11113',34);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (134,3,'11113',35);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (154,4,'11113',36);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (12,5,'11113',37);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (35,6,'11113',38);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (21,7,'11113',39);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (33,8,'11113',40);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (331,9,'11113',41);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (254,10,'11113',42);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (423,12,'11113',43);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (314,13,'11113',44);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (36,14,'11113',45);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (241,15,'11113',46);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11113',47);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (40,0,'11114',48);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (234,1,'11114',49);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11114',50);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11114',51);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11114',52);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (312,5,'11114',53);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (325,6,'11114',54);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (251,7,'11114',55);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (363,8,'11114',56);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (31,9,'11114',57);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,10,'11114',58);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (23,12,'11114',59);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (14,13,'11114',60);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (376,14,'11114',61);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (41,15,'11114',62);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11114',63);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (40,0,'11115',64);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (234,1,'11115',65);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11115',66);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11115',67);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11115',68);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (312,5,'11115',69);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (325,6,'11115',70);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (251,7,'11115',71);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (363,8,'11115',72);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (31,9,'11115',73);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,10,'11115',74);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (23,12,'11115',75);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (14,13,'11115',76);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (376,14,'11115',77);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (41,15,'11115',78);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11115',79);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (340,0,'11116',80);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,1,'11116',81);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (243,2,'11116',82);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (134,3,'11116',83);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (554,4,'11116',84);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (312,5,'11116',85);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (25,6,'11116',86);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (51,7,'11116',87);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (63,8,'11116',88);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (361,9,'11116',89);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,10,'11116',90);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (243,12,'11116',91);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (154,13,'11116',92);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (76,14,'11116',93);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (461,15,'11116',94);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11116',95);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (40,0,'11117',96);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (344,1,'11117',97);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11117',98);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11117',99);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11117',100);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (12,5,'11117',101);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (255,6,'11117',102);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (531,7,'11117',103);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (453,8,'11117',104);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,9,'11117',105);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (544,10,'11117',106);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,12,'11117',107);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,13,'11117',108);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (436,14,'11117',109);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,15,'11117',110);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11117',111);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (340,0,'11118',112);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (44,1,'11118',113);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (243,2,'11118',114);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (434,3,'11118',115);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (254,4,'11118',116);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (112,5,'11118',117);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (55,6,'11118',118);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (31,7,'11118',119);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (53,8,'11118',120);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (261,9,'11118',121);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (44,10,'11118',122);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (243,12,'11118',123);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (254,13,'11118',124);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (36,14,'11118',125);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (261,15,'11118',126);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11118',127);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (40,0,'11119',128);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (344,1,'11119',129);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11119',130);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11119',131);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11119',132);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (12,5,'11119',133);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (525,6,'11119',134);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (331,7,'11119',135);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (543,8,'11119',136);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,9,'11119',137);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (444,10,'11119',138);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,12,'11119',139);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,13,'11119',140);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (356,14,'11119',141);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,15,'11119',142);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11119',143);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (40,0,'11120',144);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (344,1,'11120',145);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11120',146);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11120',147);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11120',148);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (12,5,'11120',149);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (525,6,'11120',150);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (331,7,'11120',151);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (543,8,'11120',152);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,9,'11120',153);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (444,10,'11120',154);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,12,'11120',155);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,13,'11120',156);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (356,14,'11120',157);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,15,'11120',158);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11120',159);
REM INSERTING into LANA.CIGARRILLO
SET DEFINE OFF;
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (18,0,0,1,0,'Winston',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (19,1,1,1,0,'Nobel',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (20,3,1,1,0,'Nobel',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (21,0,1,1,0,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (22,1,1,1,0,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (23,3,1,1,0,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (24,0,1,1,1,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (25,0,1,1,0,'Malboro',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (26,0,1,0,0,'Celtas',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (27,0,1,0,0,'Ducados',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (28,0,1,1,0,'LM',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (29,0,1,1,1,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (16,0,0,1,0,'Winston',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (15,1,0,1,0,'Camel',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (14,0,0,1,0,'Camel',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (13,0,1,0,0,'Corona',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (12,0,1,1,0,'Chesterfield',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (11,1,1,1,0,'LM',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (10,0,1,1,0,'LM',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (9,0,1,0,0,'Ducados',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (8,0,0,0,0,'Celtas',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (7,0,1,0,0,'Celtas',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (6,0,1,1,0,'Malboro',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (5,0,1,1,1,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (4,3,1,1,0,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (3,1,1,1,0,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (2,0,1,1,0,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (1,3,1,1,0,'Nobel',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (0,1,1,1,0,'Nobel',null);
REM INSERTING into LANA.COMPRA
SET DEFINE OFF;
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (11,to_date('01-01-96','DD-MM-RR'),2,143,'11111',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (12,to_date('01-01-96','DD-MM-RR'),2,314,'11111',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (13,to_date('01-01-96','DD-MM-RR'),2,226,'11111',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (26,to_date('01-OCT-96','DD-MM-RR'),2,354,'11112',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (27,to_date('04-01-96','DD-MM-RR'),2,523,'11112',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (28,to_date('13-01-96','DD-MM-RR'),2,514,'11112',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (29,to_date('20-01-96','DD-MM-RR'),2,336,'11112',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (42,to_date('01-JUN-96','DD-MM-RR'),2,354,'11113',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (43,to_date('27-01-96','DD-MM-RR'),2,623,'11113',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (44,to_date('01-JUL-96','DD-MM-RR'),2,514,'11113',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (45,to_date('01-OCT-96','DD-MM-RR'),2,536,'11113',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (58,to_date('01-AUG-96','DD-MM-RR'),2,754,'11114',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (59,to_date('01-MAR-96','DD-MM-RR'),2,223,'11114',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (60,to_date('01-NOV-96','DD-MM-RR'),2,314,'11114',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (61,to_date('01-APR-96','DD-MM-RR'),2,676,'11114',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (74,to_date('01-JUL-96','DD-MM-RR'),2,454,'11115',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (75,to_date('01-JUN-96','DD-MM-RR'),2,223,'11115',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (76,to_date('01-FEB-96','DD-MM-RR'),2,314,'11115',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (77,to_date('01-MAR-96','DD-MM-RR'),2,576,'11115',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (91,to_date('01-MAR-96','DD-MM-RR'),2,454,'11116',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (92,to_date('01-01-95','DD-MM-RR'),2,543,'11116',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (93,to_date('01-FEB-96','DD-MM-RR'),2,554,'11116',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (94,to_date('18-01-96','DD-MM-RR'),2,476,'11116',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (107,to_date('01-01-96','DD-MM-RR'),2,644,'11117',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (108,to_date('01-01-96','DD-MM-RR'),2,343,'11117',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (109,to_date('01-01-96','DD-MM-RR'),2,254,'11117',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (110,to_date('01-01-96','DD-MM-RR'),2,636,'11117',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (123,to_date('01-MAY-96','DD-MM-RR'),2,444,'11118',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (124,to_date('01-01-95','DD-MM-RR'),2,543,'11118',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (125,to_date('01-01-95','DD-MM-RR'),2,554,'11118',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (126,to_date('01-01-96','DD-MM-RR'),2,436,'11118',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (140,to_date('01-01-95','DD-MM-RR'),2,544,'11119',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (141,to_date('01-01-95','DD-MM-RR'),2,543,'11119',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (142,to_date('01-01-95','DD-MM-RR'),2,454,'11119',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (143,to_date('01-JUL-96','DD-MM-RR'),2,556,'11119',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (156,to_date('01-01-95','DD-MM-RR'),2,744,'11120',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (157,to_date('01-01-95','DD-MM-RR'),2,343,'11120',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (158,to_date('01-01-95','DD-MM-RR'),2,454,'11120',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (159,to_date('01-01-96','DD-MM-RR'),2,656,'11120',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (15,to_date('22-MAY-95','DD-MM-RR'),2,401,'11111',18);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (16,to_date('01-01-95','DD-MM-RR'),2,300,'11112',19);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (17,to_date('01-MAR-96','DD-MM-RR'),2,234,'11112',20);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (18,to_date('01-JUN-96','DD-MM-RR'),2,343,'11112',21);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (19,to_date('01-FEB-96','DD-MM-RR'),2,234,'11112',22);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (20,to_date('01-01-95','DD-MM-RR'),2,154,'11112',23);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (21,to_date('03-01-96','DD-MM-RR'),2,312,'11112',24);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (22,to_date('01-FEB-96','DD-MM-RR'),2,435,'11112',25);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (23,to_date('01-NOV-96','DD-MM-RR'),2,521,'11112',26);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (24,to_date('01-MAY-96','DD-MM-RR'),2,633,'11112',27);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (25,to_date('01-MAY-96','DD-MM-RR'),2,331,'11112',28);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (31,to_date('22-MAY-95','DD-MM-RR'),2,401,'11112',18);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (32,to_date('21-01-96','DD-MM-RR'),2,400,'11113',19);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (33,to_date('02-01-96','DD-MM-RR'),2,504,'11113',20);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (34,to_date('01-01-96','DD-MM-RR'),2,743,'11113',21);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (35,to_date('01-01-96','DD-MM-RR'),2,334,'11113',22);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (36,to_date('01-MAR-96','DD-MM-RR'),2,554,'11113',23);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (37,to_date('01-01-95','DD-MM-RR'),2,782,'11113',24);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (38,to_date('01-JUN-96','DD-MM-RR'),2,135,'11113',25);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (39,to_date('01-01-95','DD-MM-RR'),2,721,'11113',26);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (40,to_date('01-01-95','DD-MM-RR'),2,633,'11113',27);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (41,to_date('01-01-95','DD-MM-RR'),2,831,'11113',28);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (47,to_date('22-MAY-95','DD-MM-RR'),2,401,'11113',18);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (48,to_date('01-MAY-96','DD-MM-RR'),2,440,'11114',19);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (49,to_date('01-AUG-96','DD-MM-RR'),2,634,'11114',20);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (50,to_date('01-01-95','DD-MM-RR'),2,343,'11114',21);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (51,to_date('01-01-95','DD-MM-RR'),2,434,'11114',22);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (52,to_date('01-01-95','DD-MM-RR'),2,454,'11114',23);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (53,to_date('01-01-95','DD-MM-RR'),2,512,'11114',24);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (54,to_date('01-JUL-96','DD-MM-RR'),2,425,'11114',25);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (55,to_date('01-01-95','DD-MM-RR'),2,551,'11114',26);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (56,to_date('01-NOV-96','DD-MM-RR'),2,563,'11114',27);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (57,to_date('01-01-95','DD-MM-RR'),2,331,'11114',28);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (63,to_date('22-MAY-95','DD-MM-RR'),2,401,'11114',18);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (64,to_date('01-01-95','DD-MM-RR'),2,540,'11115',19);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (65,to_date('01-APR-96','DD-MM-RR'),2,534,'11115',20);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (66,to_date('01-JUL-96','DD-MM-RR'),2,343,'11115',21);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (67,to_date('01-01-95','DD-MM-RR'),2,334,'11115',22);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (68,to_date('01-FEB-96','DD-MM-RR'),2,554,'11115',23);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (69,to_date('01-01-95','DD-MM-RR'),2,412,'11115',24);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (70,to_date('01-01-95','DD-MM-RR'),2,425,'11115',25);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (71,to_date('01-01-95','DD-MM-RR'),2,551,'11115',26);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (72,to_date('01-APR-96','DD-MM-RR'),2,463,'11115',27);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (73,to_date('01-MAR-96','DD-MM-RR'),2,331,'11115',28);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (79,to_date('22-MAY-95','DD-MM-RR'),2,401,'11115',18);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (80,to_date('01-01-95','DD-MM-RR'),2,440,'11116',19);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (81,to_date('01-APR-96','DD-MM-RR'),2,234,'11116',20);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (82,to_date('01-01-95','DD-MM-RR'),2,443,'11116',21);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (83,to_date('01-01-95','DD-MM-RR'),2,334,'11116',22);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (84,to_date('01-JUN-96','DD-MM-RR'),2,654,'11116',23);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (86,to_date('01-01-95','DD-MM-RR'),2,712,'11116',24);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (87,to_date('01-FEB-96','DD-MM-RR'),2,125,'11116',25);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (88,to_date('01-MAR-96','DD-MM-RR'),2,541,'11116',26);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (89,to_date('01-APR-96','DD-MM-RR'),2,363,'11116',27);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (90,to_date('01-01-95','DD-MM-RR'),2,661,'11116',28);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (96,to_date('22-MAY-95','DD-MM-RR'),2,401,'11116',18);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (97,to_date('01-NOV-96','DD-MM-RR'),2,340,'11117',19);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (98,to_date('01-01-95','DD-MM-RR'),2,644,'11117',20);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (99,to_date('01-APR-96','DD-MM-RR'),2,343,'11117',21);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (100,to_date('01-01-96','DD-MM-RR'),2,334,'11117',22);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (101,to_date('01-01-96','DD-MM-RR'),2,354,'11117',23);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (102,to_date('01-01-96','DD-MM-RR'),2,312,'11117',24);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (103,to_date('01-01-96','DD-MM-RR'),2,455,'11117',25);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (104,to_date('01-01-95','DD-MM-RR'),2,831,'11117',26);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (105,to_date('01-01-95','DD-MM-RR'),2,553,'11117',27);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (106,to_date('01-APR-96','DD-MM-RR'),2,681,'11117',28);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (112,to_date('22-MAY-95','DD-MM-RR'),2,401,'11117',18);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (113,to_date('13-01-96','DD-MM-RR'),2,540,'11118',19);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (114,to_date('12-01-96','DD-MM-RR'),2,344,'11118',20);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (115,to_date('14-01-96','DD-MM-RR'),2,543,'11118',21);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (116,to_date('01-01-95','DD-MM-RR'),2,534,'11118',22);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (117,to_date('01-01-96','DD-MM-RR'),2,454,'11118',23);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (118,to_date('01-01-96','DD-MM-RR'),2,512,'11118',24);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (119,to_date('01-01-96','DD-MM-RR'),2,355,'11118',25);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (120,to_date('01-01-96','DD-MM-RR'),2,231,'11118',26);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (121,to_date('01-01-95','DD-MM-RR'),2,353,'11118',27);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (122,to_date('01-01-95','DD-MM-RR'),2,661,'11118',28);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (128,to_date('22-MAY-95','DD-MM-RR'),2,401,'11118',18);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (129,to_date('01-01-95','DD-MM-RR'),2,340,'11119',19);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (130,to_date('01-MAR-96','DD-MM-RR'),2,644,'11119',20);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (131,to_date('01-APR-96','DD-MM-RR'),2,443,'11119',21);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (132,to_date('01-01-95','DD-MM-RR'),2,234,'11119',22);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (134,to_date('01-MAY-96','DD-MM-RR'),2,454,'11119',23);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (135,to_date('01-01-96','DD-MM-RR'),2,312,'11119',24);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (136,to_date('01-01-96','DD-MM-RR'),2,725,'11119',25);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (137,to_date('01-01-96','DD-MM-RR'),2,531,'11119',26);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (138,to_date('01-01-96','DD-MM-RR'),2,743,'11119',27);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (139,to_date('01-01-96','DD-MM-RR'),2,361,'11119',28);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (145,to_date('22-MAY-95','DD-MM-RR'),2,401,'11119',18);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (146,to_date('01-01-96','DD-MM-RR'),2,440,'11120',19);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (147,to_date('01-01-96','DD-MM-RR'),2,544,'11120',20);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (148,to_date('01-01-96','DD-MM-RR'),2,343,'11120',21);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (149,to_date('01-01-96','DD-MM-RR'),2,234,'11120',22);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (150,to_date('01-01-96','DD-MM-RR'),2,254,'11120',23);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (151,to_date('01-01-96','DD-MM-RR'),2,212,'11120',24);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (152,to_date('01-01-96','DD-MM-RR'),2,825,'11120',25);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (153,to_date('01-01-95','DD-MM-RR'),2,531,'11120',26);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (154,to_date('01-01-95','DD-MM-RR'),2,743,'11120',27);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (155,to_date('01-01-95','DD-MM-RR'),2,361,'11120',28);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (85,to_date('22-MAY-95','DD-MM-RR'),2,401,'11120',18);
REM INSERTING into LANA.ESTANCO
SET DEFINE OFF;
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9521,'11120','La Juana','Sevilla');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9542,'11119','La Hoguera','Sevilla');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9541,'11118','El Pilar','Sevilla');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9573,'11117','Costa Sol','C?rdoba');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9572,'11116','El Humo','C?rdoba');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9511,'11115','La Zona','C?rdoba');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9114,'11114','La Canela','Madrid');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9113,'11113','La Paloma','Madrid');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9112,'11112','El Clavel','Madrid');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9111,'11111','La Pajarita','Madrid');
REM INSERTING into LANA.FABRICANTE
SET DEFINE OFF;
Insert into LANA.FABRICANTE (NOMBRE_FABRICANTE,IDFABRICANTE,PAIS) values ('Tabacalera S. A.',0,'Espa?a');
Insert into LANA.FABRICANTE (NOMBRE_FABRICANTE,IDFABRICANTE,PAIS) values ('Philips Morris',1,'USA');
Insert into LANA.FABRICANTE (NOMBRE_FABRICANTE,IDFABRICANTE,PAIS) values ('R. J. Reynolds Tobaco Co.',2,'USA');
REM INSERTING into LANA.MANUFACTURA
SET DEFINE OFF;
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Winston',10,20,2);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Camel',10,20,2);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Chesterfield',10,20,1);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Corona',10,20,0);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('LM',10,20,0);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Ducados',10,20,0);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Celtas',10,20,0);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Malboro',10,20,2);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Fortuna',10,20,0);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Nobel',10,20,0);
REM INSERTING into LANA.VENTA
SET DEFINE OFF;
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (11,'11111',11,2,143,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (12,'11111',13,2,314,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (13,'11111',14,2,226,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (26,'11112',12,2,354,to_date('01-OCT-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (27,'11112',11,2,523,to_date('04-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (28,'11112',13,2,514,to_date('13-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (29,'11112',14,2,336,to_date('20-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (42,'11113',12,2,354,to_date('01-JUN-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (43,'11113',11,2,623,to_date('27-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (44,'11113',13,2,514,to_date('01-JUL-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (45,'11113',14,2,536,to_date('01-OCT-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (58,'11114',12,2,754,to_date('01-AUG-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (59,'11114',11,2,223,to_date('01-MAR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (60,'11114',13,2,314,to_date('01-NOV-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (61,'11114',14,2,676,to_date('01-APR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (74,'11115',12,2,454,to_date('01-JUL-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (75,'11115',11,2,223,to_date('01-JUN-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (76,'11115',13,2,314,to_date('01-FEB-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (77,'11115',14,2,576,to_date('01-MAR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (91,'11116',12,2,454,to_date('01-MAR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (92,'11116',11,2,543,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (93,'11116',13,2,554,to_date('01-FEB-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (94,'11116',14,2,476,to_date('18-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (107,'11117',12,2,644,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (108,'11117',11,2,343,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (109,'11117',13,2,254,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (110,'11117',14,2,636,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (123,'11118',12,2,444,to_date('01-MAY-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (124,'11118',11,2,543,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (125,'11118',13,2,554,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (126,'11118',14,2,436,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (140,'11119',12,2,544,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (141,'11119',11,2,543,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (142,'11119',13,2,454,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (143,'11119',14,2,556,to_date('01-JUL-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (156,'11120',12,2,744,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (157,'11120',11,2,343,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (158,'11120',13,2,454,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (159,'11120',14,2,656,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (14,'11111',17,2,401,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (15,'11111',18,2,401,to_date('22-MAY-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (16,'11112',19,2,300,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (17,'11112',20,2,234,to_date('01-MAR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (18,'11112',21,2,343,to_date('01-JUN-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (19,'11112',22,2,234,to_date('01-FEB-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (20,'11112',23,2,154,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (21,'11112',24,2,312,to_date('03-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (22,'11112',25,2,435,to_date('01-FEB-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (23,'11112',26,2,521,to_date('01-NOV-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (24,'11112',27,2,633,to_date('01-MAY-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (25,'11112',28,2,331,to_date('01-MAY-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (30,'11112',17,2,701,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (31,'11112',18,2,401,to_date('22-MAY-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (32,'11113',19,2,400,to_date('21-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (33,'11113',20,2,504,to_date('02-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (34,'11113',21,2,743,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (35,'11113',22,2,334,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (36,'11113',23,2,554,to_date('01-MAR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (37,'11113',24,2,782,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (38,'11113',25,2,135,to_date('01-JUN-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (39,'11113',26,2,721,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (40,'11113',27,2,633,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (41,'11113',28,2,831,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (46,'11113',17,2,641,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (47,'11113',18,2,401,to_date('22-MAY-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (48,'11114',19,2,440,to_date('01-MAY-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (49,'11114',20,2,634,to_date('01-AUG-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (50,'11114',21,2,343,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (51,'11114',22,2,434,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (52,'11114',23,2,454,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (53,'11114',24,2,512,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (54,'11114',25,2,425,to_date('01-JUL-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (55,'11114',26,2,551,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (56,'11114',27,2,563,to_date('01-NOV-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (57,'11114',28,2,331,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (62,'11114',17,2,541,to_date('01-MAY-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (63,'11114',18,2,401,to_date('22-MAY-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (64,'11115',19,2,540,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (65,'11115',20,2,534,to_date('01-APR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (66,'11115',21,2,343,to_date('01-JUL-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (67,'11115',22,2,334,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (68,'11115',23,2,554,to_date('01-FEB-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (69,'11115',24,2,412,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (70,'11115',25,2,425,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (71,'11115',26,2,551,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (72,'11115',27,2,463,to_date('01-APR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (73,'11115',28,2,331,to_date('01-MAR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (78,'11115',17,2,441,to_date('01-FEB-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (79,'11115',18,2,401,to_date('22-MAY-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (80,'11116',19,2,440,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (81,'11116',20,2,234,to_date('01-APR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (82,'11116',21,2,443,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (83,'11116',22,2,334,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (84,'11116',23,2,654,to_date('01-JUN-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (86,'11116',24,2,712,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (87,'11116',25,2,125,to_date('01-FEB-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (88,'11116',26,2,541,to_date('01-MAR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (89,'11116',27,2,363,to_date('01-APR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (90,'11116',28,2,661,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (95,'11116',17,2,661,to_date('15-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (96,'11116',18,2,401,to_date('22-MAY-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (97,'11117',19,2,340,to_date('01-NOV-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (98,'11117',20,2,644,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (99,'11117',21,2,343,to_date('01-APR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (100,'11117',22,2,334,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (101,'11117',23,2,354,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (102,'11117',24,2,312,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (103,'11117',25,2,455,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (104,'11117',26,2,831,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (105,'11117',27,2,553,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (106,'11117',28,2,681,to_date('01-APR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (111,'11117',17,2,261,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (112,'11117',18,2,401,to_date('22-MAY-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (113,'11118',19,2,540,to_date('13-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (114,'11118',20,2,344,to_date('12-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (115,'11118',21,2,543,to_date('14-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (116,'11118',22,2,534,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (117,'11118',23,2,454,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (118,'11118',24,2,512,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (119,'11118',25,2,355,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (120,'11118',26,2,231,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (121,'11118',27,2,353,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (122,'11118',28,2,661,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (127,'11118',17,2,661,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (128,'11118',18,2,401,to_date('22-MAY-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (129,'11119',19,2,340,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (130,'11119',20,2,644,to_date('01-MAR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (131,'11119',21,2,443,to_date('01-APR-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (132,'11119',22,2,234,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (134,'11119',23,2,454,to_date('01-MAY-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (135,'11119',24,2,312,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (136,'11119',25,2,725,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (137,'11119',26,2,531,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (138,'11119',27,2,743,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (139,'11119',28,2,361,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (144,'11119',17,2,361,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (145,'11119',18,2,401,to_date('22-MAY-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (146,'11120',19,2,440,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (147,'11120',20,2,544,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (148,'11120',21,2,343,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (149,'11120',22,2,234,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (150,'11120',23,2,254,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (151,'11120',24,2,212,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (152,'11120',25,2,825,to_date('01-01-96','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (153,'11120',26,2,531,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (154,'11120',27,2,743,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (155,'11120',28,2,361,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (162,'11120',17,2,761,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (85,'11120',18,2,401,to_date('22-MAY-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (160,'11120',17,2,761,to_date('01-01-95','DD-MM-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (161,'11120',18,2,401,to_date('22-MAY-95','DD-MM-RR'));
--------------------------------------------------------
--  DDL for Index CIGARRILLO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."CIGARRILLO_PK" ON "LANA"."CIGARRILLO" ("IDCIGARRILLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MANUFACTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."MANUFACTURA_PK" ON "LANA"."MANUFACTURA" ("MARCA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FABRICANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."FABRICANTE_PK" ON "LANA"."FABRICANTE" ("IDFABRICANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTANCOS_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."ESTANCOS_PK1" ON "LANA"."ESTANCO" ("NUMFISCAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMPRAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."COMPRAS_PK" ON "LANA"."COMPRA" ("NUMCOMPRA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VENTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."VENTAS_PK" ON "LANA"."VENTA" ("NUMVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTANCOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."ESTANCOS_PK" ON "LANA"."ESTANCO" ("NUMEXP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CHECK_NUMFISCAL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "LANA"."CHECK_NUMFISCAL" 
AFTER INSERT OR UPDATE
ON ESTANCO
DECLARE
  idNew VARCHAR(50);
  lengthException EXCEPTION;
BEGIN
  SELECT ESTANCO.NUMFISCAL INTO idNew FROM ESTANCO;
  IF LENGTH(idNew) < 12 THEN
  RAISE lengthException;
  END IF;
  EXCEPTION
  WHEN lengthException THEN
  dbms_output.put_line('NUMFISCAL is INVALID. It must be 12 digits long!'); 
END;
/
ALTER TRIGGER "LANA"."CHECK_NUMFISCAL" ENABLE;
--------------------------------------------------------
--  DDL for Procedure DELETEALMACEN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETEALMACEN" 
/*borra un almacen de acuerdo al IDALMACEN recibido*/
 (idalmacen_p IN NUMBER) AS
 BEGIN
    DELETE FROM ALMACEN
    WHERE ALMACEN.IDALMACEN = idalmacen_p;
 END deleteAlmacen;

/
--------------------------------------------------------
--  DDL for Procedure DELETECIGARRILLO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETECIGARRILLO" 
/*borra un cigarrillo de acuerdo al IDCIGARRILLO recibido*/
 (idcigarrillo_p IN NUMBER) AS
 BEGIN
    DELETE FROM CIGARRILLO
    WHERE CIGARRILLO.IDCIGARRILLO = idcigarrillo_p;
 END deleteCigarrillo;

/
--------------------------------------------------------
--  DDL for Procedure DELETECOMPRA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETECOMPRA" 
/*borra una compra de acuerdo al NUMCOMPRA recibido*/
 (numcompra_p IN NUMBER) AS
 BEGIN
    DELETE FROM COMPRA
    WHERE COMPRA.NUMCOMPRA = numcompra_p;
 END deleteCompra;

/
--------------------------------------------------------
--  DDL for Procedure DELETEESTANCO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETEESTANCO" 
/*borra un estanco de acuerdo al NUMEXP recibido*/
 (numfis_p IN VARCHAR2) AS
 BEGIN
    DELETE FROM ESTANCO
    WHERE ESTANCO.NUMFISCAL = numfis_p;
 END deleteEstanco;

/
--------------------------------------------------------
--  DDL for Procedure DELETEFABRICANTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETEFABRICANTE" 
/*borra un fabricante de acuerdo al IDFABRICANTE recibido*/
 (idfabricante_p IN NUMBER) AS
 BEGIN
    DELETE FROM FABRICANTE
    WHERE FABRICANTE.IDFABRICANTE = idfabricante_p;
 END deleteFabricante;

/
--------------------------------------------------------
--  DDL for Procedure DELETEMANUFACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETEMANUFACTURA" 
/*borra un registro de manufactura de acuerdo a la marca recibida*/
 (marca_p IN VARCHAR2) AS
 BEGIN
    DELETE FROM MANUFACTURA
    WHERE MANUFACTURA.MARCA = marca_p;
 END deleteManufactura;

/
--------------------------------------------------------
--  DDL for Procedure DELETEVENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETEVENTA" 
/*borra una venta de acuerdo al NUMVENTA recibido*/
 (numventa_p IN NUMBER) AS
 BEGIN
    DELETE FROM VENTA
    WHERE VENTA.NUMVENTA = numventa_p;
 END deleteVenta;

/
--------------------------------------------------------
--  DDL for Procedure INCISO1
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INCISO1" AS 
    tempval CIGARRILLO.MARCA%TYPE;
    tempcountry FABRICANTE.PAIS%TYPE;
BEGIN
    --Obtener todas las marcas de cigarrillos extranjeros.
    SELECT cig.MARCA, fab.PAIS
    INTO tempval,tempcountry
    FROM CIGARRILLO cig
    INNER JOIN FABRICANTE fab
    ON cig.IDFABRICANTE = fab.IDFABRICANTE
    WHERE (fab.PAIS != 'ESPANA');
END INCISO1;

/
--------------------------------------------------------
--  DDL for Procedure INCISO2
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INCISO2" AS
    num NUMBER;
BEGIN
    SELECT SUM(ven.PRECIOVENTA)
    INTO NUM
    FROM Cigarrillo cig
    INNER JOIN Venta ven
    ON cig.IDCIGARRILLO = ven.IDCIGARRILLO
    WHERE ven.FECHAV = '1996-22-08' AND cig.Marca = 'Winston';
END INCISO2;

/
--------------------------------------------------------
--  DDL for Procedure INSERTALMACEN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTALMACEN" 
/*insert estanco*/
 (existencia_p IN VARCHAR2, idcigarrillo_p IN NUMBER, numfiscal_p IN VARCHAR2) AS
    lastAlmacenId ALMACEN.IDALMACEN%TYPE;
    a_comment VARCHAR2(200) :='new row was inserted correctly';
 BEGIN
    INSERT INTO ALMACEN(IDALMACEN, EXISTENCIA, IDCIGARRILLO, NUMFISCAL) VALUES(lastAlmacenId + 1,existencia_p, idcigarrillo_p, numfiscal_p);
    DBMS_OUTPUT.PUT_LINE(a_comment);
 END insertAlmacen;

/
--------------------------------------------------------
--  DDL for Procedure INSERTCIGARRILLO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTCIGARRILLO" 
/*insert cigarrillo*/
 (contaminante_p IN NUMBER, filtro_p IN NUMBER, hoja_p IN NUMBER, marca_p IN VARCHAR2, mentol_p IN NUMBER) AS
    lastCigarrilloId CIGARRILLO.IDCIGARRILLO%TYPE;
 BEGIN
    SELECT IDCIGARRILLO
    INTO lastCigarrilloId
    FROM CIGARRILLO
    WHERE IDCIGARRILLO = (select max(IDCIGARRILLO) from CIGARRILLO);
    INSERT INTO CIGARRILLO(IDCIGARRILLO, CONTAMINANTE, FILTRO, HOJA, MARCA, MENTOLADO) VALUES (lastCigarrilloId + 1, contaminante_p,
                            filtro_p, hoja_p, marca_p, mentol_p);
 END insertCigarrillo;

/
--------------------------------------------------------
--  DDL for Procedure INSERTCOMPRA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTCOMPRA" 
/*insert compra*/
 (fechac_p IN DATE, preciocompra_p IN FLOAT, cantidad_p IN NUMBER, numfisp IN NUMBER, IDCIGARRILLO_p IN NUMBER) AS
    lastCompraId COMPRA.NUMCOMPRA%TYPE;
 BEGIN
    SELECT NUMCOMPRA
    INTO lastCompraId
    FROM COMPRA
    WHERE NUMCOMPRA = (select max(NUMCOMPRA) from COMPRA);
    INSERT INTO COMPRA(NUMCOMPRA, FECHAC, PRECIOCOMPRA, CANTIDAD, NUMFISCAL, IDCIGARRILLO) VALUES (lastCompraId + 1, fechac_p, preciocompra_p,
                    cantidad_p, numfisp, IDCIGARRILLO_p);
 END insertCompra;

/
--------------------------------------------------------
--  DDL for Procedure INSERTESTANCO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTESTANCO" 
/*insert estanco*/
 (lastNumFis IN VARCHAR2, numexp_p IN NUMBER, nombre_p IN VARCHAR2, provincia_p IN VARCHAR2) AS
    a_comment VARCHAR2(200) :='new row was inserted correctly';
 BEGIN
    INSERT INTO ESTANCO(NUMFISCAL, NUMEXP, NOMBRE, PROVINCIA) VALUES(lastNumFis, numexp_p, nombre_p, provincia_p);
    DBMS_OUTPUT.PUT_LINE(a_comment);
 END insertEstanco;

/
--------------------------------------------------------
--  DDL for Procedure INSERTFABRICANTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTFABRICANTE" 
(nombre_p IN VARCHAR2, pais_p IN VARCHAR2) AS 
   lastFabricanteId FABRICANTE.IDFABRICANTE%TYPE;
 BEGIN
    SELECT IDFABRICANTE
    INTO lastFabricanteId
    FROM FABRICANTE
    WHERE IDFABRICANTE = (select max(IDFABRICANTE) from FABRICANTE);
    INSERT INTO FABRICANTE(IDFABRICANTE, NOMBRE_FABRICANTE, PAIS) VALUES(lastFabricanteId + 1, nombre_p, pais_p);
 END insertFabricante;

/
--------------------------------------------------------
--  DDL for Procedure INSERTMANUFACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTMANUFACTURA" 
/*insert manufactura*/
 (marca_p IN VARCHAR2, carton_p IN NUMBER, embalaje_p IN NUMBER, idfabricante_p IN NUMBER) AS
 BEGIN
    INSERT INTO MANUFACTURA(MARCA,CARTON,EMBALAJE,IDFABRICANTE) VALUES(marca_p,carton_p,embalaje_p,idfabricante_p);
 END insertManufactura;

/
--------------------------------------------------------
--  DDL for Procedure INSERTVENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTVENTA" 
/*inserta una nueva venta*/
 (nimfisp IN NUMBER, idcigarrillop IN NUMBER, precioventa_p IN NUMBER, cantidad_p IN NUMBER, fechav_p IN DATE) AS
    lastVentaId VENTA.NUMVENTA%TYPE;
 BEGIN
    SELECT NUMVENTA
    INTO lastVentaId
    FROM VENTA
    WHERE NUMVENTA = (select max(NUMVENTA) from VENTA);
    INSERT INTO VENTA(NUMVENTA, NUMFISCAL, IDCIGARRILLO, PRECIOVENTA, CANTIDAD, FECHAV)
        VALUES(lastVentaId + 1, nimfisp, idcigarrillop, precioventa_p, cantidad_p, fechav_p);
 END insertVenta;

/
--------------------------------------------------------
--  DDL for Procedure PROCVENTAS_MENORES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."PROCVENTAS_MENORES" 

/*Procedimiento para obtener las marcas de cigarrillos para los cuales se hayan vendido menos de una determinada
cantidad (primer parametro de procedimiento), eliminando todas estas marcas en el almac�n de un determinado estanco,
cuyo NIF constituye el segundo par�metro del procedimiento.*/

 (amountp IN NUMBER, numestp IN NUMBER) AS --amountp es la cantidad m�nima que ocupa y numestp es el numfiscal del estanco
    marcaIdp CIGARRILLO.MARCA%TYPE;
    CURSOR ventas_menores IS
        SELECT cig.MARCA
        FROM CIGARRILLO cig
        INNER JOIN VENTA ven
        ON cig.IDCIGARRILLO = ven.IDCIGARRILLO
        WHERE (ven.NUMVENTA < amountp) AND (ven.NUMFISCAL = numestp);

        a_comment VARCHAR2(200) :='deleted: ';
 BEGIN
    OPEN ventas_menores;
    LOOP
        FETCH ventas_menores INTO marcaIdp;
        EXIT WHEN ventas_menores%NOTFOUND;
        DELETE FROM ALMACEN
        WHERE marcaIdp = IDALMACEN;
        DBMS_OUTPUT.PUT_LINE(a_comment || amountp);
    END LOOP;
 END procVentas_Menores;

/
--------------------------------------------------------
--  Constraints for Table CIGARRILLO
--------------------------------------------------------

  ALTER TABLE "LANA"."CIGARRILLO" MODIFY ("IDCIGARRILLO" NOT NULL ENABLE);
  ALTER TABLE "LANA"."CIGARRILLO" ADD CONSTRAINT "CIGARRILLO_PK" PRIMARY KEY ("IDCIGARRILLO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPRA
--------------------------------------------------------

  ALTER TABLE "LANA"."COMPRA" MODIFY ("NUMCOMPRA" NOT NULL ENABLE);
  ALTER TABLE "LANA"."COMPRA" ADD CONSTRAINT "COMPRAS_PK" PRIMARY KEY ("NUMCOMPRA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "LANA"."VENTA" MODIFY ("NUMVENTA" NOT NULL ENABLE);
  ALTER TABLE "LANA"."VENTA" ADD CONSTRAINT "VENTAS_PK" PRIMARY KEY ("NUMVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTANCO
--------------------------------------------------------

  ALTER TABLE "LANA"."ESTANCO" MODIFY ("NUMFISCAL" NOT NULL ENABLE);
  ALTER TABLE "LANA"."ESTANCO" ADD CONSTRAINT "ESTANCOS_PK" PRIMARY KEY ("NUMFISCAL")
  USING INDEX (CREATE UNIQUE INDEX "LANA"."ESTANCOS_PK1" ON "LANA"."ESTANCO" ("NUMFISCAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table MANUFACTURA
--------------------------------------------------------

  ALTER TABLE "LANA"."MANUFACTURA" ADD CONSTRAINT "MANUFACTURA_PK" PRIMARY KEY ("MARCA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "LANA"."MANUFACTURA" MODIFY ("MARCA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FABRICANTE
--------------------------------------------------------

  ALTER TABLE "LANA"."FABRICANTE" ADD CONSTRAINT "FABRICANTE_PK" PRIMARY KEY ("IDFABRICANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "LANA"."FABRICANTE" MODIFY ("IDFABRICANTE" NOT NULL ENABLE);
  ALTER TABLE "LANA"."FABRICANTE" MODIFY ("NOMBRE_FABRICANTE" NOT NULL ENABLE);
