--------------------------------------------------------
--  File created - Friday-May-25-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALMACEN
--------------------------------------------------------

  CREATE TABLE "LANA"."ALMACEN" 
   (	"EXISTENCIA" NUMBER(5,0), 
	"IDCIGARRILLO" NUMBER(*,0), 
	"NUMFISCAL" VARCHAR2(20 BYTE), 
	"IDALMACEN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CIGARRILLO
--------------------------------------------------------

  CREATE TABLE "LANA"."CIGARRILLO" 
   (	"IDCIGARRILLO" NUMBER(*,0), 
	"CONTAMINANTE" NUMBER(*,0), 
	"FILTRO" NUMBER(*,0), 
	"HOJA" NUMBER(*,0), 
	"MENTOLADO" NUMBER, 
	"MARCA" VARCHAR2(30 BYTE), 
	"MED_CALIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPRA
--------------------------------------------------------

  CREATE TABLE "LANA"."COMPRA" 
   (	"NUMCOMPRA" NUMBER(*,0), 
	"FECHAC" DATE, 
	"PRECIOCOMPRA" FLOAT(126), 
	"CANTIDAD" NUMBER(3,0), 
	"NUMFISCAL" VARCHAR2(30 BYTE), 
	"IDCIGARRILLO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTANCO
--------------------------------------------------------

  CREATE TABLE "LANA"."ESTANCO" 
   (	"NUMEXP" NUMBER(*,0), 
	"NUMFISCAL" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"PROVINCIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FABRICANTE
--------------------------------------------------------

  CREATE TABLE "LANA"."FABRICANTE" 
   (	"NOMBRE_FABRICANTE" VARCHAR2(50 BYTE), 
	"IDFABRICANTE" NUMBER, 
	"PAIS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MANUFACTURA
--------------------------------------------------------

  CREATE TABLE "LANA"."MANUFACTURA" 
   (	"MARCA" VARCHAR2(30 BYTE), 
	"CARTON" NUMBER, 
	"EMBALAJE" NUMBER, 
	"IDFABRICANTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "LANA"."VENTA" 
   (	"NUMVENTA" NUMBER(*,0), 
	"NUMFISCAL" VARCHAR2(30 BYTE), 
	"IDCIGARRILLO" NUMBER, 
	"PRECIOVENTA" NUMBER, 
	"CANTIDAD" NUMBER, 
	"FECHAV" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into LANA.ALMACEN
SET DEFINE OFF;
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (200,0,'11111',0);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,1,'11111',1);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (143,2,'11111',2);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (234,3,'11111',3);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11111',4);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (12,5,'11111',5);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (65,6,'11111',6);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (321,7,'11111',7);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,8,'11111',8);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (231,9,'11111',9);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,10,'11111',10);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,12,'11111',11);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (214,13,'11111',12);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (126,14,'11111',13);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (301,15,'11111',14);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11111',15);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (100,0,'11112',16);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (134,1,'11112',17);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11112',18);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11112',19);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11112',20);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (112,5,'11112',21);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (235,6,'11112',22);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (421,7,'11112',23);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (433,8,'11112',24);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (231,9,'11112',25);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,10,'11112',26);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (423,12,'11112',27);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (14,13,'11112',28);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (136,14,'11112',29);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,15,'11112',30);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11112',31);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (200,0,'11113',32);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,1,'11113',33);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (243,2,'11113',34);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (134,3,'11113',35);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (154,4,'11113',36);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (12,5,'11113',37);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (35,6,'11113',38);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (21,7,'11113',39);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (33,8,'11113',40);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (331,9,'11113',41);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (254,10,'11113',42);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (423,12,'11113',43);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (314,13,'11113',44);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (36,14,'11113',45);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (241,15,'11113',46);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11113',47);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (40,0,'11114',48);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (234,1,'11114',49);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11114',50);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11114',51);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11114',52);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (312,5,'11114',53);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (325,6,'11114',54);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (251,7,'11114',55);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (363,8,'11114',56);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (31,9,'11114',57);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,10,'11114',58);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (23,12,'11114',59);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (14,13,'11114',60);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (376,14,'11114',61);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (41,15,'11114',62);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11114',63);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (40,0,'11115',64);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (234,1,'11115',65);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11115',66);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11115',67);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11115',68);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (312,5,'11115',69);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (325,6,'11115',70);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (251,7,'11115',71);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (363,8,'11115',72);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (31,9,'11115',73);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,10,'11115',74);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (23,12,'11115',75);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (14,13,'11115',76);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (376,14,'11115',77);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (41,15,'11115',78);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11115',79);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (340,0,'11116',80);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,1,'11116',81);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (243,2,'11116',82);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (134,3,'11116',83);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (554,4,'11116',84);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (312,5,'11116',85);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (25,6,'11116',86);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (51,7,'11116',87);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (63,8,'11116',88);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (361,9,'11116',89);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,10,'11116',90);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (243,12,'11116',91);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (154,13,'11116',92);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (76,14,'11116',93);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (461,15,'11116',94);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11116',95);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (40,0,'11117',96);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (344,1,'11117',97);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11117',98);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11117',99);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11117',100);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (12,5,'11117',101);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (255,6,'11117',102);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (531,7,'11117',103);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (453,8,'11117',104);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,9,'11117',105);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (544,10,'11117',106);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,12,'11117',107);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,13,'11117',108);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (436,14,'11117',109);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,15,'11117',110);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11117',111);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (340,0,'11118',112);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (44,1,'11118',113);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (243,2,'11118',114);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (434,3,'11118',115);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (254,4,'11118',116);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (112,5,'11118',117);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (55,6,'11118',118);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (31,7,'11118',119);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (53,8,'11118',120);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (261,9,'11118',121);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (44,10,'11118',122);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (243,12,'11118',123);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (254,13,'11118',124);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (36,14,'11118',125);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (261,15,'11118',126);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11118',127);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (40,0,'11119',128);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (344,1,'11119',129);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11119',130);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11119',131);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11119',132);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (12,5,'11119',133);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (525,6,'11119',134);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (331,7,'11119',135);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (543,8,'11119',136);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,9,'11119',137);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (444,10,'11119',138);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,12,'11119',139);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,13,'11119',140);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (356,14,'11119',141);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,15,'11119',142);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11119',143);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (40,0,'11120',144);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (344,1,'11120',145);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,2,'11120',146);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (34,3,'11120',147);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,4,'11120',148);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (12,5,'11120',149);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (525,6,'11120',150);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (331,7,'11120',151);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (543,8,'11120',152);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,9,'11120',153);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (444,10,'11120',154);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (43,12,'11120',155);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (54,13,'11120',156);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (356,14,'11120',157);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (61,15,'11120',158);
Insert into LANA.ALMACEN (EXISTENCIA,IDCIGARRILLO,NUMFISCAL,IDALMACEN) values (201,16,'11120',159);
REM INSERTING into LANA.CIGARRILLO
SET DEFINE OFF;
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (0,1,1,1,0,'Nobel',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (1,3,1,1,0,'Nobel',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (2,0,1,1,0,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (3,1,1,1,0,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (4,3,1,1,0,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (5,0,1,1,1,'Fortuna',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (6,0,1,1,0,'Malboro',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (7,0,1,0,0,'Celtas',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (8,0,0,0,0,'Celtas',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (9,0,1,0,0,'Ducados',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (10,0,1,1,0,'LM',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (11,1,1,1,0,'LM',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (12,0,1,1,0,'Chesterfield',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (13,0,1,0,0,'Corona',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (14,0,0,1,0,'Camel',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (15,1,0,1,0,'Camel',null);
Insert into LANA.CIGARRILLO (IDCIGARRILLO,CONTAMINANTE,FILTRO,HOJA,MENTOLADO,MARCA,MED_CALIDAD) values (16,0,0,1,0,'Winston',null);
REM INSERTING into LANA.COMPRA
SET DEFINE OFF;
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (0,to_date('02-JAN-96','DD-MON-RR'),170,400,'11111',0);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (1,to_date('03-JAN-96','DD-MON-RR'),180,234,'11111',1);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (2,to_date('01-MAR-96','DD-MON-RR'),170,443,'11111',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (3,to_date('02-JAN-97','DD-MON-RR'),180,334,'11111',3);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (4,to_date('04-JAN-96','DD-MON-RR'),190,154,'11111',4);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (5,to_date('01-JAN-95','DD-MON-RR'),170,112,'11111',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (6,to_date('03-JAN-96','DD-MON-RR'),290,165,'11111',6);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (7,to_date('01-MAR-96','DD-MON-RR'),150,421,'11111',8);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (8,to_date('01-JAN-96','DD-MON-RR'),170,143,'11111',9);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (9,to_date('01-JAN-96','DD-MON-RR'),170,431,'11111',10);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (10,to_date('01-JAN-96','DD-MON-RR'),180,154,'11111',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (11,to_date('01-JAN-96','DD-MON-RR'),270,143,'11111',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (12,to_date('01-JAN-96','DD-MON-RR'),180,314,'11111',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (13,to_date('01-JAN-96','DD-MON-RR'),170,226,'11111',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (14,to_date('01-JAN-96','DD-MON-RR'),190,401,'11111',15);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (15,to_date('22-MAY-95','DD-MON-RR'),290,401,'11111',16);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (16,to_date('01-JAN-95','DD-MON-RR'),170,300,'11112',0);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (17,to_date('01-MAR-96','DD-MON-RR'),180,234,'11112',1);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (18,to_date('01-JUN-96','DD-MON-RR'),170,343,'11112',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (19,to_date('01-FEB-96','DD-MON-RR'),180,234,'11112',3);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (20,to_date('01-JAN-95','DD-MON-RR'),190,154,'11112',4);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (21,to_date('03-JAN-96','DD-MON-RR'),170,312,'11112',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (22,to_date('01-FEB-96','DD-MON-RR'),290,435,'11112',6);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (23,to_date('01-NOV-96','DD-MON-RR'),150,521,'11112',7);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (24,to_date('01-MAY-96','DD-MON-RR'),170,633,'11112',9);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (25,to_date('01-MAY-96','DD-MON-RR'),170,331,'11112',10);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (26,to_date('01-OCT-96','DD-MON-RR'),180,354,'11112',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (27,to_date('04-JAN-96','DD-MON-RR'),270,523,'11112',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (28,to_date('13-JAN-96','DD-MON-RR'),180,514,'11112',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (29,to_date('20-JAN-96','DD-MON-RR'),170,336,'11112',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (30,to_date('01-JAN-95','DD-MON-RR'),190,701,'11112',15);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (31,to_date('22-MAY-95','DD-MON-RR'),290,401,'11112',16);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (32,to_date('21-JAN-96','DD-MON-RR'),170,400,'11113',0);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (33,to_date('02-JAN-96','DD-MON-RR'),180,504,'11113',1);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (34,to_date('01-JAN-96','DD-MON-RR'),170,743,'11113',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (35,to_date('01-JAN-96','DD-MON-RR'),180,334,'11113',3);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (36,to_date('01-MAR-96','DD-MON-RR'),190,554,'11113',4);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (37,to_date('01-JAN-95','DD-MON-RR'),170,782,'11113',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (38,to_date('01-JUN-96','DD-MON-RR'),290,135,'11113',6);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (39,to_date('01-JAN-95','DD-MON-RR'),150,721,'11113',7);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (40,to_date('01-JAN-95','DD-MON-RR'),170,633,'11113',9);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (41,to_date('01-JAN-95','DD-MON-RR'),170,831,'11113',10);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (42,to_date('01-JUN-96','DD-MON-RR'),180,354,'11113',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (43,to_date('27-JAN-96','DD-MON-RR'),270,623,'11113',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (44,to_date('01-JUL-96','DD-MON-RR'),180,514,'11113',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (45,to_date('01-OCT-96','DD-MON-RR'),170,536,'11113',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (46,to_date('01-JAN-95','DD-MON-RR'),190,641,'11113',15);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (47,to_date('22-MAY-95','DD-MON-RR'),290,401,'11113',16);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (48,to_date('01-MAY-96','DD-MON-RR'),170,440,'11114',0);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (49,to_date('01-AUG-96','DD-MON-RR'),180,634,'11114',1);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (50,to_date('01-JAN-95','DD-MON-RR'),170,343,'11114',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (51,to_date('01-JAN-95','DD-MON-RR'),180,434,'11114',3);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (52,to_date('01-JAN-95','DD-MON-RR'),190,454,'11114',4);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (53,to_date('01-JAN-95','DD-MON-RR'),170,512,'11114',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (54,to_date('01-JUL-96','DD-MON-RR'),290,425,'11114',6);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (55,to_date('01-JAN-95','DD-MON-RR'),150,551,'11114',7);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (56,to_date('01-NOV-96','DD-MON-RR'),170,563,'11114',9);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (57,to_date('01-JAN-95','DD-MON-RR'),170,331,'11114',10);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (58,to_date('01-AUG-96','DD-MON-RR'),180,754,'11114',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (59,to_date('01-MAR-96','DD-MON-RR'),270,223,'11114',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (60,to_date('01-NOV-96','DD-MON-RR'),180,314,'11114',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (61,to_date('01-APR-96','DD-MON-RR'),170,676,'11114',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (62,to_date('01-MAY-96','DD-MON-RR'),190,541,'11114',15);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (63,to_date('22-MAY-95','DD-MON-RR'),290,401,'11114',16);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (64,to_date('01-JAN-95','DD-MON-RR'),170,540,'11115',0);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (65,to_date('01-APR-96','DD-MON-RR'),180,534,'11115',1);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (66,to_date('01-JUL-96','DD-MON-RR'),170,343,'11115',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (67,to_date('01-JAN-95','DD-MON-RR'),180,334,'11115',3);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (68,to_date('01-FEB-96','DD-MON-RR'),190,554,'11115',4);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (69,to_date('01-JAN-95','DD-MON-RR'),170,412,'11115',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (70,to_date('01-JAN-95','DD-MON-RR'),290,425,'11115',6);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (71,to_date('01-JAN-95','DD-MON-RR'),150,551,'11115',7);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (72,to_date('01-APR-96','DD-MON-RR'),170,463,'11115',9);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (73,to_date('01-MAR-96','DD-MON-RR'),170,331,'11115',10);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (74,to_date('01-JUL-96','DD-MON-RR'),180,454,'11115',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (75,to_date('01-JUN-96','DD-MON-RR'),270,223,'11115',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (76,to_date('01-FEB-96','DD-MON-RR'),180,314,'11115',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (77,to_date('01-MAR-96','DD-MON-RR'),170,576,'11115',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (78,to_date('01-FEB-96','DD-MON-RR'),190,441,'11115',15);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (79,to_date('22-MAY-95','DD-MON-RR'),290,401,'11115',16);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (80,to_date('01-JAN-95','DD-MON-RR'),170,440,'11116',0);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (81,to_date('01-APR-96','DD-MON-RR'),180,234,'11116',1);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (82,to_date('01-JAN-95','DD-MON-RR'),170,443,'11116',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (83,to_date('01-JAN-95','DD-MON-RR'),180,334,'11116',3);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (84,to_date('01-JUN-96','DD-MON-RR'),190,654,'11116',4);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (85,to_date('01-JAN-95','DD-MON-RR'),170,712,'11116',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (86,to_date('01-FEB-96','DD-MON-RR'),290,125,'11116',6);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (87,to_date('01-MAR-96','DD-MON-RR'),150,541,'11116',7);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (88,to_date('01-APR-96','DD-MON-RR'),170,363,'11116',9);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (89,to_date('01-JAN-95','DD-MON-RR'),170,661,'11116',10);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (90,to_date('01-MAR-96','DD-MON-RR'),180,454,'11116',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (91,to_date('01-JAN-95','DD-MON-RR'),270,543,'11116',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (92,to_date('01-FEB-96','DD-MON-RR'),180,554,'11116',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (93,to_date('18-JAN-96','DD-MON-RR'),170,476,'11116',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (94,to_date('15-JAN-96','DD-MON-RR'),190,661,'11116',15);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (95,to_date('22-MAY-95','DD-MON-RR'),290,401,'11116',16);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (96,to_date('01-NOV-96','DD-MON-RR'),170,340,'11117',0);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (97,to_date('01-JAN-95','DD-MON-RR'),180,644,'11117',1);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (98,to_date('01-APR-96','DD-MON-RR'),170,343,'11117',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (99,to_date('01-JAN-96','DD-MON-RR'),180,334,'11117',3);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (100,to_date('01-JAN-96','DD-MON-RR'),190,354,'11117',4);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (101,to_date('01-JAN-96','DD-MON-RR'),170,312,'11117',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (102,to_date('01-JAN-96','DD-MON-RR'),290,455,'11117',6);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (103,to_date('01-JAN-95','DD-MON-RR'),150,831,'11117',7);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (104,to_date('01-JAN-95','DD-MON-RR'),170,553,'11117',9);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (105,to_date('01-APR-96','DD-MON-RR'),170,681,'11117',10);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (106,to_date('01-JAN-96','DD-MON-RR'),180,644,'11117',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (107,to_date('01-JAN-96','DD-MON-RR'),270,343,'11117',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (108,to_date('01-JAN-96','DD-MON-RR'),180,254,'11117',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (109,to_date('01-JAN-96','DD-MON-RR'),170,636,'11117',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (110,to_date('01-JAN-95','DD-MON-RR'),190,261,'11117',15);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (111,to_date('22-MAY-95','DD-MON-RR'),290,401,'11117',16);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (112,to_date('13-JAN-96','DD-MON-RR'),170,540,'11118',0);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (113,to_date('12-JAN-96','DD-MON-RR'),180,344,'11118',1);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (114,to_date('14-JAN-96','DD-MON-RR'),170,543,'11118',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (115,to_date('01-JAN-95','DD-MON-RR'),180,534,'11118',3);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (116,to_date('01-JAN-96','DD-MON-RR'),190,454,'11118',4);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (117,to_date('01-JAN-96','DD-MON-RR'),170,512,'11118',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (118,to_date('01-JAN-96','DD-MON-RR'),290,355,'11118',6);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (119,to_date('01-JAN-96','DD-MON-RR'),150,231,'11118',7);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (120,to_date('01-JAN-95','DD-MON-RR'),170,353,'11118',9);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (121,to_date('01-JAN-95','DD-MON-RR'),170,661,'11118',10);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (122,to_date('01-MAY-96','DD-MON-RR'),180,444,'11118',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (123,to_date('01-JAN-95','DD-MON-RR'),270,543,'11118',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (124,to_date('01-JAN-95','DD-MON-RR'),180,554,'11118',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (125,to_date('01-JAN-96','DD-MON-RR'),170,436,'11118',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (126,to_date('01-JAN-96','DD-MON-RR'),190,661,'11118',15);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (127,to_date('22-MAY-95','DD-MON-RR'),290,401,'11118',16);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (128,to_date('01-JAN-95','DD-MON-RR'),170,340,'11119',0);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (129,to_date('01-MAR-96','DD-MON-RR'),180,644,'11119',1);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (130,to_date('01-APR-96','DD-MON-RR'),170,443,'11119',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (131,to_date('01-JAN-95','DD-MON-RR'),180,234,'11119',3);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (132,to_date('01-MAY-96','DD-MON-RR'),190,454,'11119',4);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (133,to_date('01-JAN-96','DD-MON-RR'),170,312,'11119',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (134,to_date('01-JAN-96','DD-MON-RR'),290,725,'11119',6);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (135,to_date('01-JAN-96','DD-MON-RR'),150,531,'11119',7);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (136,to_date('01-JAN-96','DD-MON-RR'),170,743,'11119',9);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (137,to_date('01-JAN-96','DD-MON-RR'),170,361,'11119',10);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (138,to_date('01-JAN-95','DD-MON-RR'),180,544,'11119',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (139,to_date('01-JAN-95','DD-MON-RR'),270,543,'11119',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (140,to_date('01-JAN-95','DD-MON-RR'),180,454,'11119',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (141,to_date('01-JUL-96','DD-MON-RR'),170,556,'11119',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (142,to_date('01-JAN-96','DD-MON-RR'),190,361,'11119',15);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (143,to_date('22-MAY-95','DD-MON-RR'),290,401,'11119',16);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (144,to_date('01-JAN-96','DD-MON-RR'),170,440,'11120',0);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (145,to_date('01-JAN-96','DD-MON-RR'),180,544,'11120',1);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (146,to_date('01-JAN-96','DD-MON-RR'),170,343,'11120',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (147,to_date('01-JAN-96','DD-MON-RR'),180,234,'11120',3);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (148,to_date('01-JAN-96','DD-MON-RR'),190,254,'11120',4);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (149,to_date('01-JAN-96','DD-MON-RR'),170,212,'11120',2);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (150,to_date('01-JAN-96','DD-MON-RR'),290,825,'11120',6);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (151,to_date('01-JAN-95','DD-MON-RR'),150,531,'11120',7);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (152,to_date('01-JAN-95','DD-MON-RR'),170,743,'11120',9);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (153,to_date('01-JAN-95','DD-MON-RR'),170,361,'11120',10);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (154,to_date('01-JAN-95','DD-MON-RR'),180,744,'11120',11);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (155,to_date('01-JAN-95','DD-MON-RR'),270,343,'11120',12);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (156,to_date('01-JAN-95','DD-MON-RR'),180,454,'11120',13);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (157,to_date('01-JAN-96','DD-MON-RR'),170,656,'11120',14);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (158,to_date('01-JAN-95','DD-MON-RR'),190,761,'11120',15);
Insert into LANA.COMPRA (NUMCOMPRA,FECHAC,PRECIOCOMPRA,CANTIDAD,NUMFISCAL,IDCIGARRILLO) values (159,to_date('22-MAY-95','DD-MON-RR'),290,401,'11120',16);
REM INSERTING into LANA.ESTANCO
SET DEFINE OFF;
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9521,'11120','La Juana','Sevilla');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9542,'11119','La Hoguera','Sevilla');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9541,'11118','El Pilar','Sevilla');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9573,'11117','Costa Sol','C?rdoba');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9572,'11116','El Humo','C?rdoba');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9511,'11115','La Zona','C?rdoba');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9114,'11114','La Canela','Madrid');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9113,'11113','La Paloma','Madrid');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9112,'11112','El Clavel','Madrid');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9111,'11111','La Pajarita','Madrid');
Insert into LANA.ESTANCO (NUMEXP,NUMFISCAL,NOMBRE,PROVINCIA) values (9575,'1','ANA','NINGUNA');
REM INSERTING into LANA.FABRICANTE
SET DEFINE OFF;
Insert into LANA.FABRICANTE (NOMBRE_FABRICANTE,IDFABRICANTE,PAIS) values ('Tabacalera S. A.',0,'Espa?a');
Insert into LANA.FABRICANTE (NOMBRE_FABRICANTE,IDFABRICANTE,PAIS) values ('Philips Morris',1,'USA');
Insert into LANA.FABRICANTE (NOMBRE_FABRICANTE,IDFABRICANTE,PAIS) values ('R. J. Reynolds Tobaco Co.',2,'USA');
REM INSERTING into LANA.MANUFACTURA
SET DEFINE OFF;
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Winston',10,20,2);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Camel',10,20,2);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Chesterfield',10,20,1);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Corona',10,20,0);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('LM',10,20,0);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Ducados',10,20,0);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Celtas',10,20,0);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Malboro',10,20,2);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Fortuna',10,20,0);
Insert into LANA.MANUFACTURA (MARCA,CARTON,EMBALAJE,IDFABRICANTE) values ('Nobel',10,20,0);
REM INSERTING into LANA.VENTA
SET DEFINE OFF;
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (0,'11111',0,250,200,to_date('02-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (1,'11111',1,260,200,to_date('03-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (2,'11111',2,250,300,to_date('01-JUN-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (3,'11111',3,260,100,to_date('02-APR-97','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (4,'11111',4,270,100,to_date('04-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (5,'11111',2,250,100,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (6,'11111',6,320,100,to_date('03-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (7,'11111',8,240,100,to_date('01-JUN-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (8,'11111',9,265,100,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (9,'11111',10,260,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (10,'11111',11,270,100,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (11,'11111',12,320,100,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (12,'11111',13,230,100,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (13,'11111',14,290,100,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (14,'11111',15,310,100,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (15,'11111',16,410,200,to_date('22-AUG-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (16,'11112',0,250,200,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (17,'11112',1,260,100,to_date('01-JUN-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (18,'11112',2,250,300,to_date('01-SEP-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (19,'11112',3,260,200,to_date('01-MAY-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (20,'11112',4,270,100,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (21,'11112',2,250,200,to_date('03-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (22,'11112',6,320,200,to_date('01-MAY-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (23,'11112',7,240,100,to_date('01-FEB-97','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (24,'11112',9,265,200,to_date('01-AUG-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (25,'11112',10,260,100,to_date('01-AUG-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (26,'11112',11,270,300,to_date('01-JAN-97','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (27,'11112',12,320,100,to_date('04-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (28,'11112',13,230,500,to_date('13-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (29,'11112',14,290,200,to_date('20-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (30,'11112',15,310,500,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (31,'11112',16,410,200,to_date('22-AUG-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (32,'11113',0,250,200,to_date('21-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (33,'11113',1,260,471,to_date('02-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (34,'11113',2,250,500,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (35,'11113',3,260,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (36,'11113',4,270,400,to_date('01-JUN-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (37,'11113',2,260,770,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (38,'11113',6,320,100,to_date('01-SEP-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (39,'11113',7,240,700,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (40,'11113',9,265,600,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (41,'11113',10,260,500,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (42,'11113',11,270,100,to_date('01-SEP-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (43,'11113',12,320,200,to_date('27-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (44,'11113',13,230,200,to_date('01-OCT-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (45,'11113',14,290,500,to_date('01-JAN-97','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (46,'11113',15,310,400,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (47,'11113',16,410,200,to_date('22-AUG-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (48,'11114',0,250,400,to_date('01-AUG-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (49,'11114',1,260,400,to_date('01-NOV-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (50,'11114',2,250,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (51,'11114',3,260,400,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (52,'11114',4,270,400,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (53,'11114',2,250,200,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (54,'11114',6,320,100,to_date('01-OCT-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (55,'11114',7,240,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (56,'11114',9,265,200,to_date('01-FEB-97','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (57,'11114',10,260,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (58,'11114',11,270,700,to_date('01-NOV-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (59,'11114',12,320,200,to_date('01-JUN-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (60,'11114',13,230,300,to_date('01-FEB-97','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (61,'11114',14,290,300,to_date('01-JUL-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (62,'11114',15,310,500,to_date('01-AUG-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (63,'11114',16,410,200,to_date('22-AUG-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (64,'11115',0,250,500,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (65,'11115',1,260,300,to_date('01-JUL-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (66,'11115',2,250,300,to_date('01-OCT-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (67,'11115',3,260,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (68,'11115',4,270,500,to_date('01-MAY-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (69,'11115',2,250,100,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (70,'11115',6,320,100,to_date('01-MAY-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (71,'11115',7,240,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (72,'11115',9,265,100,to_date('01-JUL-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (73,'11115',10,260,300,to_date('01-JUN-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (74,'11115',11,270,400,to_date('01-OCT-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (75,'11115',12,320,200,to_date('01-SEP-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (76,'11115',13,230,300,to_date('01-MAY-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (77,'11115',14,290,200,to_date('01-JUN-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (78,'11115',15,310,400,to_date('01-MAY-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (79,'11115',16,410,200,to_date('22-AUG-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (80,'11116',0,250,100,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (81,'11116',1,260,200,to_date('01-JUL-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (82,'11116',2,250,200,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (83,'11116',3,260,200,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (84,'11116',4,270,100,to_date('01-SEP-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (85,'11116',2,250,400,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (86,'11116',6,320,100,to_date('01-MAY-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (87,'11116',7,240,490,to_date('01-JUN-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (88,'11116',9,265,300,to_date('01-JUL-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (89,'11116',10,260,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (90,'11116',11,270,400,to_date('01-JUN-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (91,'11116',12,320,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (92,'11116',13,230,400,to_date('01-MAY-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (93,'11116',14,290,400,to_date('18-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (94,'11116',15,310,200,to_date('15-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (95,'11116',16,410,200,to_date('22-AUG-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (96,'11117',0,250,300,to_date('01-FEB-97','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (97,'11117',1,260,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (98,'11117',2,250,300,to_date('01-AUG-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (99,'11117',3,260,300,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (100,'11117',4,270,300,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (101,'11117',2,250,300,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (102,'11117',6,320,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (103,'11117',7,240,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (104,'11117',9,265,100,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (105,'11117',10,260,620,to_date('01-JUL-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (106,'11117',11,270,100,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (107,'11117',12,320,300,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (108,'11117',13,230,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (109,'11117',14,290,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (110,'11117',15,310,200,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (111,'11117',16,410,200,to_date('22-AUG-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (112,'11118',0,250,200,to_date('13-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (113,'11118',1,260,300,to_date('12-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (114,'11118',2,250,300,to_date('14-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (115,'11118',3,260,100,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (116,'11118',4,270,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (117,'11118',2,250,400,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (118,'11118',6,320,300,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (119,'11118',7,240,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (120,'11118',9,265,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (121,'11118',10,260,400,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (122,'11118',11,270,400,to_date('01-AUG-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (123,'11118',12,320,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (124,'11118',13,230,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (125,'11118',14,290,400,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (126,'11118',15,310,400,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (127,'11118',16,410,200,to_date('22-AUG-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (128,'11119',0,250,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (129,'11119',1,260,300,to_date('01-JUN-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (130,'11119',2,250,400,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (131,'11119',3,260,200,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (132,'11119',4,270,400,to_date('01-AUG-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (133,'11119',2,250,300,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (134,'11119',6,320,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (135,'11119',7,240,2001,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (136,'11119',9,265,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (137,'11119',10,260,300,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (138,'11119',11,270,100,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (139,'11119',12,320,500,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (140,'11119',13,230,400,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (141,'11119',14,290,200,to_date('01-OCT-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (142,'11119',15,310,300,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (143,'11119',16,410,200,to_date('22-AUG-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (144,'11120',0,250,400,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (145,'11120',1,260,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (146,'11120',2,250,300,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (147,'11120',3,250,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (148,'11120',4,270,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (149,'11120',2,250,200,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (150,'11120',6,320,300,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (151,'11120',7,240,200,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (152,'11120',9,265,200,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (153,'11120',10,260,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (154,'11120',11,270,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (155,'11120',12,320,300,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (156,'11120',13,230,400,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (157,'11120',14,290,300,to_date('01-APR-96','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (158,'11120',15,310,700,to_date('01-APR-95','DD-MON-RR'));
Insert into LANA.VENTA (NUMVENTA,NUMFISCAL,IDCIGARRILLO,PRECIOVENTA,CANTIDAD,FECHAV) values (159,'11120',16,410,200,to_date('22-AUG-95','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index CIGARRILLO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."CIGARRILLO_PK" ON "LANA"."CIGARRILLO" ("IDCIGARRILLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MANUFACTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."MANUFACTURA_PK" ON "LANA"."MANUFACTURA" ("MARCA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FABRICANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."FABRICANTE_PK" ON "LANA"."FABRICANTE" ("IDFABRICANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTANCOS_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."ESTANCOS_PK1" ON "LANA"."ESTANCO" ("NUMFISCAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMPRAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."COMPRAS_PK" ON "LANA"."COMPRA" ("NUMCOMPRA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VENTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."VENTAS_PK" ON "LANA"."VENTA" ("NUMVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTANCOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LANA"."ESTANCOS_PK" ON "LANA"."ESTANCO" ("NUMEXP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure DELETEALMACEN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETEALMACEN" 
/*borra un almacen de acuerdo al IDALMACEN recibido*/
 (idalmacen_p IN NUMBER) AS
 BEGIN
    DELETE FROM ALMACEN
    WHERE ALMACEN.IDALMACEN = idalmacen_p;
 END deleteAlmacen;

/
--------------------------------------------------------
--  DDL for Procedure DELETECIGARRILLO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETECIGARRILLO" 
/*borra un cigarrillo de acuerdo al IDCIGARRILLO recibido*/
 (idcigarrillo_p IN NUMBER) AS
 BEGIN
    DELETE FROM CIGARRILLO
    WHERE CIGARRILLO.IDCIGARRILLO = idcigarrillo_p;
 END deleteCigarrillo;

/
--------------------------------------------------------
--  DDL for Procedure DELETECOMPRA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETECOMPRA" 
/*borra una compra de acuerdo al NUMCOMPRA recibido*/
 (numcompra_p IN NUMBER) AS
 BEGIN
    DELETE FROM COMPRA
    WHERE COMPRA.NUMCOMPRA = numcompra_p;
 END deleteCompra;

/
--------------------------------------------------------
--  DDL for Procedure DELETEESTANCO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETEESTANCO" 
/*borra un estanco de acuerdo al NUMEXP recibido*/
 (numfis_p IN VARCHAR2) AS
 BEGIN
    DELETE FROM ESTANCO
    WHERE ESTANCO.NUMFISCAL = numfis_p;
 END deleteEstanco;

/
--------------------------------------------------------
--  DDL for Procedure DELETEFABRICANTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETEFABRICANTE" 
/*borra un fabricante de acuerdo al IDFABRICANTE recibido*/
 (idfabricante_p IN NUMBER) AS
 BEGIN
    DELETE FROM FABRICANTE
    WHERE FABRICANTE.IDFABRICANTE = idfabricante_p;
 END deleteFabricante;

/
--------------------------------------------------------
--  DDL for Procedure DELETEMANUFACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETEMANUFACTURA" 
/*borra un registro de manufactura de acuerdo a la marca recibida*/
 (marca_p IN VARCHAR2) AS
 BEGIN
    DELETE FROM MANUFACTURA
    WHERE MANUFACTURA.MARCA = marca_p;
 END deleteManufactura;

/
--------------------------------------------------------
--  DDL for Procedure DELETEVENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."DELETEVENTA" 
/*borra una venta de acuerdo al NUMVENTA recibido*/
 (numventa_p IN NUMBER) AS
 BEGIN
    DELETE FROM VENTA
    WHERE VENTA.NUMVENTA = numventa_p;
 END deleteVenta;

/
--------------------------------------------------------
--  DDL for Procedure INSERTALMACEN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTALMACEN" 
/*insert estanco*/
 (existencia_p IN VARCHAR2, idcigarrillo_p IN NUMBER, numfiscal_p IN VARCHAR2) AS
    lastAlmacenId ALMACEN.IDALMACEN%TYPE;
    a_comment VARCHAR2(200) :='new row was inserted correctly';
 BEGIN
    INSERT INTO ALMACEN(IDALMACEN, EXISTENCIA, IDCIGARRILLO, NUMFISCAL) VALUES(lastAlmacenId + 1,existencia_p, idcigarrillo_p, numfiscal_p);
    DBMS_OUTPUT.PUT_LINE(a_comment);
 END insertAlmacen;

/
--------------------------------------------------------
--  DDL for Procedure INSERTCIGARRILLO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTCIGARRILLO" 
/*insert cigarrillo*/
 (contaminante_p IN NUMBER, filtro_p IN NUMBER, hoja_p IN NUMBER, marca_p IN VARCHAR2, mentol_p IN NUMBER) AS
    lastCigarrilloId CIGARRILLO.IDCIGARRILLO%TYPE;
 BEGIN
    SELECT IDCIGARRILLO
    INTO lastCigarrilloId
    FROM CIGARRILLO
    WHERE IDCIGARRILLO = (select max(IDCIGARRILLO) from CIGARRILLO);
    INSERT INTO CIGARRILLO(IDCIGARRILLO, CONTAMINANTE, FILTRO, HOJA, MARCA, MENTOLADO) VALUES (lastCigarrilloId + 1, contaminante_p,
                            filtro_p, hoja_p, marca_p, mentol_p);
 END insertCigarrillo;

/
--------------------------------------------------------
--  DDL for Procedure INSERTCOMPRA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTCOMPRA" 
/*insert compra*/
 (fechac_p IN DATE, preciocompra_p IN FLOAT, cantidad_p IN NUMBER, numfisp IN NUMBER, IDCIGARRILLO_p IN NUMBER) AS
    lastCompraId COMPRA.NUMCOMPRA%TYPE;
 BEGIN
    SELECT NUMCOMPRA
    INTO lastCompraId
    FROM COMPRA
    WHERE NUMCOMPRA = (select max(NUMCOMPRA) from COMPRA);
    INSERT INTO COMPRA(NUMCOMPRA, FECHAC, PRECIOCOMPRA, CANTIDAD, NUMFISCAL, IDCIGARRILLO) VALUES (lastCompraId + 1, fechac_p, preciocompra_p,
                    cantidad_p, numfisp, IDCIGARRILLO_p);
 END insertCompra;

/
--------------------------------------------------------
--  DDL for Procedure INSERTESTANCO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTESTANCO" 
/*insert estanco*/
 (lastNumFis IN VARCHAR2, numexp_p IN NUMBER, nombre_p IN VARCHAR2, provincia_p IN VARCHAR2) AS
    a_comment VARCHAR2(200) :='new row was inserted correctly';
 BEGIN
    INSERT INTO ESTANCO(NUMFISCAL, NUMEXP, NOMBRE, PROVINCIA) VALUES(lastNumFis, numexp_p, nombre_p, provincia_p);
    DBMS_OUTPUT.PUT_LINE(a_comment);
 END insertEstanco;

/
--------------------------------------------------------
--  DDL for Procedure INSERTFABRICANTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTFABRICANTE" 
(nombre_p IN VARCHAR2, pais_p IN VARCHAR2) AS 
   lastFabricanteId FABRICANTE.IDFABRICANTE%TYPE;
 BEGIN
    SELECT IDFABRICANTE
    INTO lastFabricanteId
    FROM FABRICANTE
    WHERE IDFABRICANTE = (select max(IDFABRICANTE) from FABRICANTE);
    INSERT INTO FABRICANTE(IDFABRICANTE, NOMBRE_FABRICANTE, PAIS) VALUES(lastFabricanteId + 1, nombre_p, pais_p);
 END insertFabricante;

/
--------------------------------------------------------
--  DDL for Procedure INSERTMANUFACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTMANUFACTURA" 
/*insert manufactura*/
 (marca_p IN VARCHAR2, carton_p IN NUMBER, embalaje_p IN NUMBER, idfabricante_p IN NUMBER) AS
 BEGIN
    INSERT INTO MANUFACTURA(MARCA,CARTON,EMBALAJE,IDFABRICANTE) VALUES(marca_p,carton_p,embalaje_p,idfabricante_p);
 END insertManufactura;

/
--------------------------------------------------------
--  DDL for Procedure INSERTVENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."INSERTVENTA" 
/*inserta una nueva venta*/
 (nimfisp IN NUMBER, idcigarrillop IN NUMBER, precioventa_p IN NUMBER, cantidad_p IN NUMBER, fechav_p IN DATE) AS
    lastVentaId VENTA.NUMVENTA%TYPE;
 BEGIN
    SELECT NUMVENTA
    INTO lastVentaId
    FROM VENTA
    WHERE NUMVENTA = (select max(NUMVENTA) from VENTA);
    INSERT INTO VENTA(NUMVENTA, NUMFISCAL, IDCIGARRILLO, PRECIOVENTA, CANTIDAD, FECHAV)
        VALUES(lastVentaId + 1, nimfisp, idcigarrillop, precioventa_p, cantidad_p, fechav_p);
 END insertVenta;

/
--------------------------------------------------------
--  DDL for Procedure PROCVENTAS_MENORES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "LANA"."PROCVENTAS_MENORES" 

/*Procedimiento para obtener las marcas de cigarrillos para los cuales se hayan vendido menos de una determinada
cantidad (primer parametro de procedimiento), eliminando todas estas marcas en el almacén de un determinado estanco,
cuyo NIF constituye el segundo parámetro del procedimiento.*/

 (amountp IN NUMBER, numestp IN VARCHAR2) AS --amountp es la cantidad mínima que ocupa y numestp es el numfiscal del estanco
    cigarrilloIdp CIGARRILLO.IDCIGARRILLO%TYPE;
    marcaIdp CIGARRILLO.MARCA%TYPE;
    CURSOR ventas_menores IS
        SELECT cig.MARCA
        FROM CIGARRILLO cig
        INNER JOIN VENTA ven
        ON cig.IDCIGARRILLO = ven.IDCIGARRILLO
        INNER JOIN ALMACEN alm
        ON alm.IDCIGARRILLO = cig.IDCIGARRILLO
        WHERE (ven.NUMVENTA < amountp) AND (ven.NUMFISCAL = numestp)
        GROUP BY cig.MARCA;

        a_comment VARCHAR2(200) :='deleted: ';
 BEGIN
    OPEN ventas_menores;
    FETCH ventas_menores INTO marcaIdp;
        WHILE ventas_menores%FOUND LOOP
        DELETE FROM ALMACEN
        WHERE cigarrilloIdp = IDCIGARRILLO;
        DBMS_OUTPUT.PUT_LINE(a_comment || amountp);
    END LOOP;
 END procVentas_Menores;

/
--------------------------------------------------------
--  Constraints for Table CIGARRILLO
--------------------------------------------------------

  ALTER TABLE "LANA"."CIGARRILLO" ADD CONSTRAINT "CIGARRILLO_PK" PRIMARY KEY ("IDCIGARRILLO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "LANA"."CIGARRILLO" MODIFY ("IDCIGARRILLO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPRA
--------------------------------------------------------

  ALTER TABLE "LANA"."COMPRA" MODIFY ("NUMCOMPRA" NOT NULL ENABLE);
  ALTER TABLE "LANA"."COMPRA" ADD CONSTRAINT "COMPRAS_PK" PRIMARY KEY ("NUMCOMPRA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "LANA"."VENTA" MODIFY ("NUMVENTA" NOT NULL ENABLE);
  ALTER TABLE "LANA"."VENTA" ADD CONSTRAINT "VENTAS_PK" PRIMARY KEY ("NUMVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTANCO
--------------------------------------------------------

  ALTER TABLE "LANA"."ESTANCO" MODIFY ("NUMFISCAL" NOT NULL ENABLE);
  ALTER TABLE "LANA"."ESTANCO" ADD CONSTRAINT "ESTANCOS_PK" PRIMARY KEY ("NUMFISCAL")
  USING INDEX (CREATE UNIQUE INDEX "LANA"."ESTANCOS_PK1" ON "LANA"."ESTANCO" ("NUMFISCAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "LANA"."ESTANCO" ADD CONSTRAINT "NUMFISCALCHK" CHECK (length(NUMFISCAL) < 12) DISABLE;
--------------------------------------------------------
--  Constraints for Table MANUFACTURA
--------------------------------------------------------

  ALTER TABLE "LANA"."MANUFACTURA" ADD CONSTRAINT "MANUFACTURA_PK" PRIMARY KEY ("MARCA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "LANA"."MANUFACTURA" MODIFY ("MARCA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FABRICANTE
--------------------------------------------------------

  ALTER TABLE "LANA"."FABRICANTE" ADD CONSTRAINT "FABRICANTE_PK" PRIMARY KEY ("IDFABRICANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "LANA"."FABRICANTE" MODIFY ("IDFABRICANTE" NOT NULL ENABLE);
  ALTER TABLE "LANA"."FABRICANTE" MODIFY ("NOMBRE_FABRICANTE" NOT NULL ENABLE);
